#!/usr/bin/env python3
"""Scans the site for screenshot placeholders (data-file="NN-slug") and rewrites SHOTLIST.md,
so the shot list always matches what the pages actually use.
Run: python3 tools/list_shots.py"""
import os, re, glob, collections
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# What each capture should show. Keep in step with the alt text on the pages.
SPEC = {
 "01-hero-horde": ("Clean", "A zombie group in the middle distance, the player as a silhouette in the foreground. Low angle, golden hour or fog, wide lens. Leave the upper-right third fairly empty: the title sits bottom-left on the game page."),
 "02-hero-rider": ("Clean", "The player on horseback on a ridge or road. Side or three-quarter view, long shadows."),
 "03-hero-flooded-city": ("Clean", "The flooded capital. Wide establishing shot, moody light, water reflections and reeds visible."),
 "05-combat-melee": ("HUD", "A melee swing at a zombie, mid-action, zombie clearly readable."),
 "09-loot-drop": ("HUD", "Loot items on the ground beside a fresh corpse, with the E pickup prompt showing."),
 "10-inventory": ("UI", "The backpack window open and filled with items. No empty grid."),
 "11-weapon-wheel": ("HUD", "The Q weapon wheel open, several weapons carried so few slots are greyed out."),
 "13-build-mode": ("Build UI", "Build mode open with the palette visible and a prop half-placed (placement ring showing)."),
 "14-character-creator": ("Creator UI", "The character creator with a styled survivor on the pedestal."),
 "15-world-grassland": ("Clean", "Grassland and flower fields with a forest and horizon behind. No player."),
 "16-world-forest": ("Clean", "Dense spruce forest in the north, ideally with light shafts or snow. No player."),
 "17-world-night": ("Clean", "A recognisable place at night (a town street or the flooded city). No player, or a tiny one."),
 "18-wildlife": ("Clean", "Wildlife grazing or herding in a field. Very wide: this one is shown as a letterbox strip, so keep the subject in the middle band."),
 "20-cutaway-view": ("Gameplay camera", "The player inside or behind a building with the cutaway circle open, showing the interior through the wall."),
}
OPTIONAL = {
 "04-hero-survivor-closeup": "Player character, upper body, shallow depth of field.",
 "06-combat-firearm": "Aiming a pistol or rifle with the reticle visible.",
 "07-combat-bow": "Bow drawn on a target.",
 "08-zombie-lunge": "A zombie mid-lunge toward the camera.",
 "12-horseback-hud": "Riding with gait, stamina and minimap visible.",
 "19-main-menu": "The main menu (once it no longer says Developer Mode).",
}

uses = collections.defaultdict(list)
for f in sorted(glob.glob(os.path.join(ROOT, "**", "*.html"), recursive=True)):
    rel = os.path.relpath(f, ROOT).replace(os.sep, "/")
    if rel.startswith(("_unpublished", "tabletop", "rules", "posts/")): continue
    page = "/" + rel.replace("index.html", "")
    text = open(f).read()
    for m in re.finditer(r'<figure class="([^"]*)" data-file="([^"]+)"', text):
        cls, name = m.group(1), m.group(2)
        before = text[max(0, m.start()-120):m.start()]
        if "door-art" in before: where = "homepage door (tall, crops to the centre)"
        elif "hero-shot" in cls and "/posts/" in page: where = "post header banner (21:9)"
        elif "hero-shot" in cls: where = "full-screen hero"
        elif 'class="dive"' in before: where = "deep-dive card"
        elif "thumb" in cls: where = "latest-posts card"
        elif "wide" in cls: where = "letterbox strip"
        elif "<figcaption>" in text[m.start():m.start()+400]: where = "photo mosaic"
        else: where = "feature section"
        uses[name].append(f"`{page}` {where}")

have = {os.path.splitext(os.path.basename(p))[0] for p in glob.glob(os.path.join(ROOT, "images", "game", "*.webp"))}
out = ["# Screenshot manifest",
"",
"Generated by `tools/list_shots.py` from the placeholders on the site. Every row is one image the site is waiting for.",
"",
"**How to deliver**",
"- Capture at **3840x2160 (16:9) PNG**, post-processing on, no editor gizmos, no debug text.",
"- Name the file **exactly** as in the File column (e.g. `05-combat-melee.png`).",
"- Put them in one folder and hand them over. Claude converts them to `images/game/<file>.webp` and they appear on the site automatically; nothing else needs linking.",
"- Take 2 or 3 variations of each; add `-a`, `-b` to the name (e.g. `05-combat-melee-b.png`) and we pick the best.",
"- Clean = HUD hidden. HUD = HUD visible.",
"",
"## On the site now (%d)" % len(uses), "",
"| Done | File | HUD | What to capture | Where it appears |", "|---|---|---|---|---|"]
for name in sorted(uses):
    hud, what = SPEC.get(name, ("?", "(no description yet)"))
    done = "✅" if name in have else "⬜"
    out.append(f"| {done} | `{name}` | {hud} | {what} | {'<br>'.join(dict.fromkeys(uses[name]))} |")
out += ["", "## Optional extras (not placed on the site yet)", "", "| File | What to capture |", "|---|---|"]
for name, what in OPTIONAL.items():
    out.append(f"| `{name}` | {what} |")
out += ["", "## Priority if short on time", "",
"`01-hero-horde` (used on both the homepage door and the game hero), `03-hero-flooded-city`, `15-world-grassland`, `05-combat-melee`, `02-hero-rider`, `09-loot-drop`, `14-character-creator`.",
"",
"## Before the shoot",
"- Zombies are switched off in the current build: turn them on for 01, 05, 09.",
"- Wait for this week's colour grading pass before the hero shots (01, 02, 03).",
"- Avoid sparse building interiors and the \"Developer Mode\" main menu.",
"- Never commit raw captures to the Unity repo."]
open(os.path.join(ROOT, "SHOTLIST.md"), "w").write("\n".join(out) + "\n")
print(len(uses), "placeholders;", sum(n in have for n in uses), "delivered")
missing = [n for n in uses if n not in SPEC]
if missing: print("no description for:", missing)
